import Head from 'next/head';
import { Container, Stack, Badge } from 'react-bootstrap';
import { useState, useEffect } from 'react';
const Categories = () => {
  const [categories, setCategories] = useState([{ id: '', name: '' }]);
  const fetchCategories = async () => {
    const res = await fetch('http://localhost:3000/api/categories');
    const data = await res.json();
    return data;
  };

  useEffect(() => {
    fetchCategories().then((data) => {
      setCategories(data);
    });
  }, []);
  return (
    <div>
      <Head>
        <title>Categories</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main
        className='vh-100 d-flex
        align-items-center justify-content-center
      '
      >
        {/* vertical align center */}
        <Container
          className='

        vh-25
        '
        >
          <Stack
            direction='horizontal'
            gap={1}
            className='d-flex flex-wrap 
          justify-content-center
          vh-50
          my-2'
          >
            {categories.map((category, index) => (
                // encode the category name to be used in the url
              <a
                href={`/category/${category.id}?category=${encodeURIComponent(category.name)}`}
                key={index}
                className='mx-1'
              >
                <Badge bg='dark' pill>
                  {category.name}
                </Badge>
              </a>
            ))}
          </Stack>
        </Container>
      </main>
    </div>
  );
};

export default Categories;
